### PR TITLE
Fixed some mistakes

### PR DESCRIPTION
**Pull request by acallesalda**
I made some mistakes in the new Examples.hs - now fixed.

### CODE REVIEW

**Comment by asr** [comment]
I couldn't merge because "this branch has conflicts that must be resolved". Please fix the problem.

**Comment by asr** [comment]
You can merge the PR.

**Comment by acallesalda** [comment]
The web interface show me no "merge pull request" as this site says (https://help.github.com/articles/merging-a-pull-request/). Do I have write access to this repository?

**Comment by asr** [comment]
> Do I have write access to this repository?

You have not answered the invitation to collaborate in this repository.

**Comment by asr** [comment]
I cancelled the previous invitation and I created a new one. Do you get the invitation?

**Comment by acallesalda** [comment]
Yeah, thanks. Sorry for that, I'm still very new to github.

**Pull request merged**
